num1 = int(input("ВВедите 1 число: "))
num2 = int(input("ВВедите 2 число: "))
num3 = int(input("ВВедите 3 число: "))
num4 = int(input("ВВедите 4 число: "))
print(f"Среднее арифметическое: {(num1 + num2 + num3 + num4) / 4}")